# Generated by Django 3.0.5 on 2020-04-28 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('short', '0003_auto_20200429_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='click',
            name='url_hash',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='short.URL'),
        ),
    ]
